name: DEPENDENCIES

on:
  push:
    branches: [ main ]

jobs:
  
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      
      - name: Step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha' > alpha.html
          echo 'bravo' > bravo.html
          echo 'charlie' > charlie.html
          cd ..

      - name: Step 3 - Use the Upload  Artifact Github Actions 
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: download