name: SECRETS

# Para configurar el secrets, se debe ir a:
# Settings -> Secrets -> New repository secret
# Name: SECRET_TOKEN Value:TrustNoOne
# Nota: Al acceder al Secret, el valor no aparecerá, siempre está oculto

on:
  push:
    branches: [ main ]

jobs:
  
  secrets-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Echo out a Github Actions Secret to the logs
        run: |
          echo "The Github Actions Secret will be marked:"
          echo ${{ secrets.SECRET_TOKEN }}
          # Salida: ***
          echo "Trick to echo Github Actions Secret:"
          echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'
          # Al hacer esto se puede revelar el contenido
      
      -name: Step 2 - if statement
        # No es necesario especificar el shell
        shell: bash
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST == 'TrustNo1'
        run: echo "I know the secret"